# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/cp/zmp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/cp/zmp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/cp/zmp/CMakeFiles /home/user/cp/zmp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/cp/zmp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MediaPlayer

# Build rule for target.
MediaPlayer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MediaPlayer
.PHONY : MediaPlayer

# fast build rule for target.
MediaPlayer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/build
.PHONY : MediaPlayer/fast

#=============================================================================
# Target rules for targets named MediaPlayer_autogen_timestamp_deps

# Build rule for target.
MediaPlayer_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MediaPlayer_autogen_timestamp_deps
.PHONY : MediaPlayer_autogen_timestamp_deps

# fast build rule for target.
MediaPlayer_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer_autogen_timestamp_deps.dir/build.make CMakeFiles/MediaPlayer_autogen_timestamp_deps.dir/build
.PHONY : MediaPlayer_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named MediaPlayer_autogen

# Build rule for target.
MediaPlayer_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MediaPlayer_autogen
.PHONY : MediaPlayer_autogen

# fast build rule for target.
MediaPlayer_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer_autogen.dir/build.make CMakeFiles/MediaPlayer_autogen.dir/build
.PHONY : MediaPlayer_autogen/fast

MediaPlayer_autogen/mocs_compilation.o: MediaPlayer_autogen/mocs_compilation.cpp.o
.PHONY : MediaPlayer_autogen/mocs_compilation.o

# target to build an object file
MediaPlayer_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/MediaPlayer_autogen/mocs_compilation.cpp.o
.PHONY : MediaPlayer_autogen/mocs_compilation.cpp.o

MediaPlayer_autogen/mocs_compilation.i: MediaPlayer_autogen/mocs_compilation.cpp.i
.PHONY : MediaPlayer_autogen/mocs_compilation.i

# target to preprocess a source file
MediaPlayer_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/MediaPlayer_autogen/mocs_compilation.cpp.i
.PHONY : MediaPlayer_autogen/mocs_compilation.cpp.i

MediaPlayer_autogen/mocs_compilation.s: MediaPlayer_autogen/mocs_compilation.cpp.s
.PHONY : MediaPlayer_autogen/mocs_compilation.s

# target to generate assembly for a file
MediaPlayer_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/MediaPlayer_autogen/mocs_compilation.cpp.s
.PHONY : MediaPlayer_autogen/mocs_compilation.cpp.s

audiomanager.o: audiomanager.cpp.o
.PHONY : audiomanager.o

# target to build an object file
audiomanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/audiomanager.cpp.o
.PHONY : audiomanager.cpp.o

audiomanager.i: audiomanager.cpp.i
.PHONY : audiomanager.i

# target to preprocess a source file
audiomanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/audiomanager.cpp.i
.PHONY : audiomanager.cpp.i

audiomanager.s: audiomanager.cpp.s
.PHONY : audiomanager.s

# target to generate assembly for a file
audiomanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/audiomanager.cpp.s
.PHONY : audiomanager.cpp.s

deviceswidget.o: deviceswidget.cpp.o
.PHONY : deviceswidget.o

# target to build an object file
deviceswidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/deviceswidget.cpp.o
.PHONY : deviceswidget.cpp.o

deviceswidget.i: deviceswidget.cpp.i
.PHONY : deviceswidget.i

# target to preprocess a source file
deviceswidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/deviceswidget.cpp.i
.PHONY : deviceswidget.cpp.i

deviceswidget.s: deviceswidget.cpp.s
.PHONY : deviceswidget.s

# target to generate assembly for a file
deviceswidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/deviceswidget.cpp.s
.PHONY : deviceswidget.cpp.s

equalizerwidget.o: equalizerwidget.cpp.o
.PHONY : equalizerwidget.o

# target to build an object file
equalizerwidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/equalizerwidget.cpp.o
.PHONY : equalizerwidget.cpp.o

equalizerwidget.i: equalizerwidget.cpp.i
.PHONY : equalizerwidget.i

# target to preprocess a source file
equalizerwidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/equalizerwidget.cpp.i
.PHONY : equalizerwidget.cpp.i

equalizerwidget.s: equalizerwidget.cpp.s
.PHONY : equalizerwidget.s

# target to generate assembly for a file
equalizerwidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/equalizerwidget.cpp.s
.PHONY : equalizerwidget.cpp.s

fileswidget.o: fileswidget.cpp.o
.PHONY : fileswidget.o

# target to build an object file
fileswidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/fileswidget.cpp.o
.PHONY : fileswidget.cpp.o

fileswidget.i: fileswidget.cpp.i
.PHONY : fileswidget.i

# target to preprocess a source file
fileswidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/fileswidget.cpp.i
.PHONY : fileswidget.cpp.i

fileswidget.s: fileswidget.cpp.s
.PHONY : fileswidget.s

# target to generate assembly for a file
fileswidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/fileswidget.cpp.s
.PHONY : fileswidget.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o
.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

playerwidget.o: playerwidget.cpp.o
.PHONY : playerwidget.o

# target to build an object file
playerwidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/playerwidget.cpp.o
.PHONY : playerwidget.cpp.o

playerwidget.i: playerwidget.cpp.i
.PHONY : playerwidget.i

# target to preprocess a source file
playerwidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/playerwidget.cpp.i
.PHONY : playerwidget.cpp.i

playerwidget.s: playerwidget.cpp.s
.PHONY : playerwidget.s

# target to generate assembly for a file
playerwidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/playerwidget.cpp.s
.PHONY : playerwidget.cpp.s

playlistswidget.o: playlistswidget.cpp.o
.PHONY : playlistswidget.o

# target to build an object file
playlistswidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/playlistswidget.cpp.o
.PHONY : playlistswidget.cpp.o

playlistswidget.i: playlistswidget.cpp.i
.PHONY : playlistswidget.i

# target to preprocess a source file
playlistswidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/playlistswidget.cpp.i
.PHONY : playlistswidget.cpp.i

playlistswidget.s: playlistswidget.cpp.s
.PHONY : playlistswidget.s

# target to generate assembly for a file
playlistswidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/playlistswidget.cpp.s
.PHONY : playlistswidget.cpp.s

settingswidget.o: settingswidget.cpp.o
.PHONY : settingswidget.o

# target to build an object file
settingswidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/settingswidget.cpp.o
.PHONY : settingswidget.cpp.o

settingswidget.i: settingswidget.cpp.i
.PHONY : settingswidget.i

# target to preprocess a source file
settingswidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/settingswidget.cpp.i
.PHONY : settingswidget.cpp.i

settingswidget.s: settingswidget.cpp.s
.PHONY : settingswidget.s

# target to generate assembly for a file
settingswidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayer.dir/build.make CMakeFiles/MediaPlayer.dir/settingswidget.cpp.s
.PHONY : settingswidget.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MediaPlayer_autogen"
	@echo "... MediaPlayer_autogen_timestamp_deps"
	@echo "... MediaPlayer"
	@echo "... MediaPlayer_autogen/mocs_compilation.o"
	@echo "... MediaPlayer_autogen/mocs_compilation.i"
	@echo "... MediaPlayer_autogen/mocs_compilation.s"
	@echo "... audiomanager.o"
	@echo "... audiomanager.i"
	@echo "... audiomanager.s"
	@echo "... deviceswidget.o"
	@echo "... deviceswidget.i"
	@echo "... deviceswidget.s"
	@echo "... equalizerwidget.o"
	@echo "... equalizerwidget.i"
	@echo "... equalizerwidget.s"
	@echo "... fileswidget.o"
	@echo "... fileswidget.i"
	@echo "... fileswidget.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... playerwidget.o"
	@echo "... playerwidget.i"
	@echo "... playerwidget.s"
	@echo "... playlistswidget.o"
	@echo "... playlistswidget.i"
	@echo "... playlistswidget.s"
	@echo "... settingswidget.o"
	@echo "... settingswidget.i"
	@echo "... settingswidget.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

